
disqus_shortname: jrblog-1

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://julian-robinson.github.io

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Julian-Robinson/julian-robinson.github.io
